//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int IDChiTietDonHang { get; set; }
        public int IDDonHang { get; set; }
        public Nullable<int> IDBienThe { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public string TenSanPham { get; set; }
        public string TenMau { get; set; }
        public string TenKichThuoc { get; set; }
    
        public virtual BienTheSanPham BienTheSanPham { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}
