//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaChi
    {
        public int IDDiaChi { get; set; }
        public int IDNguoiDung { get; set; }
        public string TenNguoiNhan { get; set; }
        public string SoDienThoai { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<bool> LaMacDinh { get; set; }
        public string PhuongXa1 { get; set; }
        public string QuanHuyen1 { get; set; }
        public string TinhThanh1 { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
