//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public int IDDonHang { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public Nullable<int> IDMaGiamGia { get; set; }
        public string TenNguoiNhan { get; set; }
        public string DiaChiGiao { get; set; }
        public string SoDienThoai { get; set; }
        public decimal TongTienHang { get; set; }
        public Nullable<decimal> PhiVanChuyen { get; set; }
        public Nullable<decimal> TienGiamGia { get; set; }
        public decimal TongThanhToan { get; set; }
        public Nullable<int> IDPhuongThucThanhToan { get; set; }
        public int IDTrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual MaGiamGia MaGiamGia { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual PhuongThucThanhToan PhuongThucThanhToan { get; set; }
        public virtual TrangThaiDonHang TrangThaiDonHang { get; set; }
    }
}
