//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int IDNguoiDung { get; set; }
        public int IDBienThe { get; set; }
        public int SoLuong { get; set; }
    
        public virtual BienTheSanPham BienTheSanPham { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
