//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HinhAnh()
        {
            this.HinhAnh_BienThe = new HashSet<HinhAnh_BienThe>();
        }
    
        public int IDHinhAnh { get; set; }
        public string DuongDan { get; set; }
        public string MoTa { get; set; }
        public string VectorDacTrung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnh_BienThe> HinhAnh_BienThe { get; set; }
    }
}
