//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnh_BienThe
    {
        public int IDHinhAnh { get; set; }
        public int IDBienThe { get; set; }
        public Nullable<bool> LaAnhChinh { get; set; }
    
        public virtual BienTheSanPham BienTheSanPham { get; set; }
        public virtual HinhAnh HinhAnh { get; set; }
    }
}
