//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaGiamGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaGiamGia()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int IDMaGiamGia { get; set; }
        public string MaCode { get; set; }
        public string TenChuongTrinh { get; set; }
        public int LoaiGiamGia { get; set; }
        public decimal GiaTri { get; set; }
        public Nullable<decimal> DonHangToiThieu { get; set; }
        public Nullable<decimal> GiamToiDa { get; set; }
        public int SoLuong { get; set; }
        public int DaSuDung { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public bool TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
