//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.BienTheSanPhams = new HashSet<BienTheSanPham>();
        }
    
        public int IDSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> IDDanhMuc { get; set; }
        public Nullable<int> IDThuongHieu { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public decimal Gia { get; set; }
        public Nullable<decimal> GiaKhuyenMai { get; set; }
        public Nullable<System.DateTime> NgayBatDauKM { get; set; }
        public Nullable<System.DateTime> NgayKetThucKM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienTheSanPham> BienTheSanPhams { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
